## VISHVA PATEL

## Assignment for Lab Session on September 30

## <u> Multivariate Analysis</u>



* For the Iris dataset, Consider random vector X = (Sepal Length, Sepal Width, Petal Length, Petal Width). Write Python code to perform the following tasks without using any readymade functions for performing tests of hypothesis.

1. Obtain unbiased estimators of mean vector and variance-covariance matrix for each of the three species.
2. Test whether the mean vector for Setosa is equal to (5, 3.5, 1.5, 0.25).
3. Test whether mean vector for versicolor is same as that of virginica.

* Now Perform tasks 2 and 3 using the library functions, and compare the results with the above results obtained by you.

In [1]:
import pandas as pd
import numpy as np
from pydataset import data
iris = data("iris")
iris.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
1           5.1          3.5           1.4          0.2  setosa
2           4.9          3.0           1.4          0.2  setosa
3           4.7          3.2           1.3          0.2  setosa
4           4.6          3.1           1.5          0.2  setosa
5           5.0          3.6           1.4          0.2  setosa

In [2]:
setosa = iris[iris['Species'] =='setosa'].iloc[:,0:4]
versicolor = iris[iris['Species'] =='versicolor'].iloc[:,0:4]
virginica = iris[iris['Species'] =='virginica'].iloc[:,0:4]

## 1. Obtain unbiased estimators of mean vector and variance-covariance matrix for each of the three species.

## Unbiased estimators of mean vector for each Species

In [3]:
setosa_mean = setosa.mean()
versicolor_mean = versicolor.mean()
virginica_mean = virginica.mean()
print("Unbiased estimator of Mean vector for setosa Species:", tuple(round(setosa_mean,5)))
print("Unbiased estimator of Mean vector for versicolor Species:", tuple(round(versicolor_mean,5)))
print("Unbiased estimator of Mean vector for virginica Species:", tuple(round(virginica_mean,5)))

Unbiased estimator of Mean vector for setosa Species: (5.006, 3.428, 1.462, 0.246)
Unbiased estimator of Mean vector for versicolor Species: (5.936, 2.77, 4.26, 1.326)
Unbiased estimator of Mean vector for virginica Species: (6.588, 2.974, 5.552, 2.026)


## Unbiased estimators of var-cov vector for each Species : 

In [4]:
n1 = setosa.count()
n2 = versicolor.count()
n3 = virginica.count()

var_setosa = n1/(n1-1) * setosa.cov()
var_versicolor = n2/(n2-1) * versicolor.cov()
var_virginica = n3/(n3-1) * virginica.cov()
print("Unbiased estimator of variance-covariance for setosa species: \n \n ",var_setosa)
print("Unbiased estimator of variance-covariance for versicolor species: \n \n ",var_versicolor)
print("Unbiased estimator of variance-covariance for virginica species: \n \n ",var_virginica)

Unbiased estimator of variance-covariance for setosa species: 
 
                Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
Sepal.Length      0.126785     0.101241      0.016689     0.010541
Sepal.Width       0.101241     0.146622      0.011937     0.009488
Petal.Length      0.016689     0.011937      0.030775     0.006193
Petal.Width       0.010541     0.009488      0.006193     0.011333
Unbiased estimator of variance-covariance for versicolor species: 
 
                Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
Sepal.Length      0.271870     0.086922      0.186631     0.056918
Sepal.Width       0.086922     0.100479      0.084340     0.042045
Petal.Length      0.186631     0.084340      0.225323     0.074594
Petal.Width       0.056918     0.042045      0.074594     0.039904
Unbiased estimator of variance-covariance for virginica species: 
 
                Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
Sepal.Length      0.412595     0.095677      0.309479  

## 2. Test whether the mean vector for Setosa is equal to (5, 3.5, 1.5, 0.25).
### ***One sample Hotelling T sqaure test***

## Hypothesis
#### H0 : µ1 = µ0 (Mean vector for setosa equals to (5,3.5,1.5,0.25))
#### H1 : µ1 ≠ µ0 (Mean vetor for setosa does not equals to (5,3.5,1.5,0.25))

In [5]:
mu0 = np.array([5,3.5,1.5,0.25])
mu0 = mu0[:,np.newaxis]
Xbar = np.array(setosa_mean)
xbar = Xbar[:,np.newaxis]
S = (len(setosa)-1)* var_setosa
S

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
Sepal.Length      6.212449     4.960816      0.817755     0.516531
Sepal.Width       4.960816     7.184490      0.584898     0.464898
Petal.Length      0.817755     0.584898      1.507959     0.303469
Petal.Width       0.516531     0.464898      0.303469     0.555306

In [6]:
Hott_Tsquare = len(setosa)*(len(setosa)-1)*((xbar-mu0).T @ (np.linalg.inv(S)) @ (xbar-mu0))
print(Hott_Tsquare)
Hott_tsquare = float(Hott_Tsquare)
print("Test statistics is:",Hott_tsquare)

[[7.42369352]]
Test statistics is: 7.423693518613591


In [7]:
Fcal = (((len(setosa)-4)/4) * Hott_tsquare)/(len(setosa)-1)
Fcal

1.742295417633802

In [8]:
from scipy import stats
## using table value at alpha = 0.05
Ftab = stats.f.ppf(q = 1 - 0.05, dfn=4, dfd=len(setosa)-4)
print("F-table value:",Ftab)
if Fcal < Ftab:
    print("We do not reject the H0.")
else:
    print("we reject the H0.")

F-table value: 2.574035025183231
We do not reject the H0.


In [9]:
## using P -value
from scipy import stats
pvalue = stats.f.sf(Fcal, 4, 50-4)
print("p-value value:",pvalue)
if pvalue < 0.05:
    print("We reject the H0.")
else:
    print("we do not reject the H0.")

p-value value: 0.15695745305997597
we do not reject the H0.


**Conclusion : Here, Fcal < Ftab  <u>or</u>  P-value > 0.05. So we do not reject null hypothesis and we can say that Mean vetor for setosa equals to (5,3.5,1.5,0.25).**

## Using library functions

In [10]:
import pingouin as pg
m0 = [5,3.5,1.5,0.25]
pg.multivariate_ttest(setosa,m0)

T2         F  df1  df2     pval
hotelling  7.575197  1.777852    4   46  0.14953

## Here, we can see that for testing Mean vector for setosa equals to (5,3.5,1.5,0.25) with and without libraries we got almost same output.

## 3. Test whether mean vector for versicolor is same as that of virginica.
### ***Two sample Hotelling T sqaure test***

## Hypothesis:
#### H0 : µ1 = µ2 (Mean vector for versicolor is same as that of virginica.)
#### H1 : µ1 ≠ µ2 (Mean vector for versicolor is not same as that of virginica.)


In [11]:
S_inv = np.linalg.inv((var_versicolor*49+49*var_virginica)/98)
print(S_inv)
X1 = np.array(versicolor_mean)
print(X1)
X2 = np.array(virginica_mean)
print(X2)

[[  9.49362872  -3.14629917  -8.51520132   2.8120894 ]
 [ -3.14629917  16.76828127   0.45810295 -10.61179937]
 [ -8.51520132   0.45810295  12.94730194  -6.34104387]
 [  2.8120894  -10.61179937  -6.34104387  29.517534  ]]
[5.936 2.77  4.26  1.326]
[6.588 2.974 5.552 2.026]


In [12]:
Tsq = ((50*50)/100)*((X1-X2).T) @ S_inv @ (X1-X2)
print("Test Statistics",Tsq)

Test Statistics 348.362702295075


In [13]:
Fcal = ((50+50-4-1)/((50+50-2)*4))*Tsq
Fcal

84.42463448477582

In [14]:
## using table value at alpha = 0.05
Ftab = stats.f.ppf(q = 1 - 0.05, dfn=4, dfd=50+50-4-1)
print("F-table value:",Ftab)
if Fcal < Ftab:
    print("We do not reject the H0.")
else:
    print("we reject the H0.")

F-table value: 2.4674936234496485
we reject the H0.


In [15]:
## using P -value
from scipy import stats
pvalue = stats.f.sf(Fcal, 4, 50+50-4-1)
print("p-value value:",pvalue)
if pvalue < 0.05:
    print("We reject the H0.")
else:
    print("we do not reject the H0.")

p-value value: 2.0121515989508464e-30
We reject the H0.


**Conclusion : Here, Fcal > Ftab  <u>or</u>  P-value < 0.05. So we reject null hypothesis and we can say that Mean vector for versicolor is not same as that of virginica.**

## Using library functions

In [16]:
pg.multivariate_ttest(versicolor,virginica,paired = False)

T2          F  df1  df2          pval
hotelling  355.472145  86.147586    4   95  9.539876e-31

## Here, we can see that for testing Mean vector for versicolor and Mean vector for virginica with and without libraries we got almost same output.