In [1]:
# Gram Schmidt Method (modified)

from math import *

n = int(input("Enter number of rows: "))
p = int(input("Enter number of columns: "))

X = []

print("Enter matrix:")
for i in range(n):
    X.append(list(map(float, input().split())))

x_copy = X.copy()

V = [[0] * p for i in range(n)]
T = [[0] * p for i in range(p)]

for k in range(p):

    # Find norm
    s = 0
    for i in range(n):
        s = s + x_copy[i][k] ** 2

    d = sqrt(s)
    
    if d < e :
        print("Matrix is not full column rank")
        break
        
    # Find unit vector
    for i in range(n):
        V[i][k] = x_copy[i][k] / d

    # Find T
    for j in range(k, p):
        s = 0
        for i in range(n):
            s = s + V[i][k] * X[i][j]

        T[k][j] = s

    # Make remaining columns orthogonal
    for j in range(k + 1, p):
        for i in range(n):
            x_copy[i][j] = x_copy[i][j] - T[k][j] * V[i][k]

print("Matrix V:")
for i in range(n):
    for j in range(p):
        print(round(V[i][j], 4), end="\t")
    print()

print("Matrix T:")
for i in range(p):
    for j in range(p):
        print(round(T[i][j], 4), end="\t")
    print()

Enter number of rows:  2
Enter number of columns:  2


Enter matrix:


 2 3
 4 6


Matrix is not full column rank
Matrix V:
0.4472	0	
0.8944	0	
Matrix T:
4.4721	6.7082	
0	0	


In [4]:
# Householder Transformation

import numpy as np

n =  int(input("Enter the number of rows: "))
p =  int(input("Enter the number of columns: "))

x = np.zeros((n,p))

for i in range(n):
    for j in range(p):
        x[i,j] = float(input(f"enter x[{i+1},{j+1}]"))

print("original matrix x: ")
print(x)

for k in range(min(n,p)):
    s_sq = np.sum(x[k:, k] ** 2)

    if s_sq < e:
        continue

    s = np.sqrt(s_sq)

    u = x[k:, k].copy()

    if x[k,k] < 0:
        u[0] -= s

    else:
        u[0] += s

    beta = np.dot(u,u)

    for j in range(k+1, p):
        temp = np.dot(u, x[k:, j])
        x[k:, j ] -= (u* temp)/beta

    if x[k,k] < 0:
        x[k,k] = s

    else:
        x[k,k] = -s

    x[k+1: ,k] = 0

x[np.abs(x) < 1e-10 ] = 0

print("The transformed matrix is: ")
print(np.round(x,4))

Enter the number of rows:  3
Enter the number of columns:  3
enter x[1,1] 2
enter x[1,2] 1
enter x[1,3] 3
enter x[2,1] 4
enter x[2,2] 5
enter x[2,3] 6
enter x[3,1] 7
enter x[3,2] 8
enter x[3,3] 9


original matrix x: 
[[2. 1. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
The transformed matrix is: 
[[-8.3066 -4.195  -4.0979]
 [ 0.     -5.3758 -1.0162]
 [ 0.      0.     -1.8997]]


In [6]:
# Gauss Seidel for homogenous equations

import numpy as np

n = int(input("Enter the number of unknowns: "))

a = np.zeros((n,n))

print("enter the coefficient matrix a: ")
for i in range(n):
    for j in range(n):
        a[i,j] = float(input(f" a{i+1}{j+1}: "))

print("coefficient matrix a: ")
print(a)

b = np.zeros((n,1))

for i in range(n):
    b[i] = float(input(f"Enter b{i+1}: "))

print("right side vector b: ")
print(b)

diagonal_dominant = True
for i in range(n):
    diag_element = abs(a[i,i])
    off_diagonal = 0

    for j in range(n):
        if j != i:
            off_diagonal += abs(a[i,j])

    if diag_element <= off_diagonal:
        diagonal_dominant = False

if diagonal_dominant:
    print("Matrix A is diagonally dominant.")
    print("Gauss-Seidel method is expected to converge.")

else:
    print("Matrix A is not diagonally dominant.")
    print("convergence is not guaranteed.")


x = np.zeros(n)
eps = float(input("enter the accuracy level"))
N = int(input("Enter the maximum number of iteration: "))

for k in range(N):
    x_old = x.copy()

    for i in range(n):
        p = b[i,0]

        for j in range(n):
            if j != i : 
                p = p - a[i,j] * x[j]

        x[i] = p / a[i,i]

    error =  np.max(np.abs(x-x_old))

    print(f"Iteration {k+1}: {x}")

    if error < eps:
        print("Gauss-Seidel method converged.")
        break
       
else:
    print("Maximum iterations reached.")

print("\nSolution: ")

for i in range(n):
    print(f"x{i+1} = {x[i]}")

Enter the number of unknowns:  3


enter the coefficient matrix a: 


 a11:  2
 a12:  3
 a13:  1
 a21:  4
 a22:  5
 a23:  6
 a31:  7
 a32:  8
 a33:  9


coefficient matrix a: 
[[2. 3. 1.]
 [4. 5. 6.]
 [7. 8. 9.]]


Enter b1:  2
Enter b2:  3
Enter b3:  1


right side vector b: 
[[2.]
 [3.]
 [1.]]
Matrix A is not diagonally dominant.
convergence is not guaranteed.


enter the accuracy level 0.0001
Enter the maximum number of iteration:  100


Iteration 1: [ 1.         -0.2        -0.48888889]
Iteration 2: [ 1.54444444 -0.04888889 -1.04666667]
Iteration 3: [ 1.59666667  0.57866667 -1.64511111]
Iteration 4: [ 0.95455556  1.81048889 -2.24064444]
Iteration 5: [-0.59541111  3.76510222 -2.77254889]
Iteration 6: [-3.26137889  6.53616178 -3.16218244]
Iteration 7: [-7.22315144 10.17314009 -3.3136734 ]
Iteration 8: [-12.60287343  14.65870683  -3.11661562]
Iteration 9: [-19.42975243  19.88374069  -2.45129539]
Iteration 10: [-27.59996334  25.62152514  -1.19693975]
Iteration 11: [-36.83381783  31.50338196   0.7566299 ]
Iteration 12: [-46.63338789  36.99875443   3.4937422 ]
Iteration 13: [-56.24500275  41.40351156   7.05410297]
Iteration 14: [-64.63231882  43.84093149  11.41097554]
Iteration 15: [-70.466885    43.28033736  16.44727735]
Iteration 16: [-72.14414471  38.57858294  21.93114993]
Iteration 17: [-67.83344938  28.54937959  27.49323433]
Iteration 18: [-55.57068654  12.06466804  32.60860684]
Iteration 19: [-33.40130547 -11.80928383

In [7]:
# Gauss Elimination for Homogenous Equations

import numpy as np

n = int(input("Enter number of unknowns: "))

aug = np.zeros((n,n+1))

print("Enter the augmented matrix: ")
for i in range(n):
    for j in range(n+1):
        aug[i,j] = float(input(f"aug[{i+1},{j+1}] = "))

print("\n Augmented Matrix: ")
print(aug)

for k in range(n-1):
    if aug[k,k] == 0:
        for i in range(k+1, n):
            if aug[i, k] != 0:
                a[[k, i]] = a[[i, k]]
                break

    for i in range(k+1, n):
        m = aug[i,k]/aug[k,k]
        aug[i] = aug[i] - m * aug[k]

print("\nUpper triangular matrix: ")
print(aug)

x = np.zeros(n)

for i in range(n-1, -1, -1):
    s = 0

    for j in range(i+1, n):
        s += aug[i,j] * x[j]

    x[i] = (aug[i,n] - s) / aug[i,i]

print("\nSolution: ")
for i in range(n):
    print(f"x{i+1} = {x[i]}")

Enter number of unknowns:  3


Enter the augmented matrix: 


aug[1,1] =  2
aug[1,2] =  3
aug[1,3] =  1
aug[1,4] =  2
aug[2,1] =  4
aug[2,2] =  5
aug[2,3] =  6
aug[2,4] =  3
aug[3,1] =  2
aug[3,2] =  3
aug[3,3] =  4
aug[3,4] =  1



 Augmented Matrix: 
[[2. 3. 1. 2.]
 [4. 5. 6. 3.]
 [2. 3. 4. 1.]]

Upper triangular matrix: 
[[ 2.  3.  1.  2.]
 [ 0. -1.  4. -1.]
 [ 0.  0.  3. -1.]]

Solution: 
x1 = 1.6666666666666665
x2 = -0.33333333333333326
x3 = -0.3333333333333333


In [8]:
# GAUSS JORDAN FOR MATRIX INVERSE

import numpy as np

n = int(input("Enter order of matrix: "))

# Enter matrix
A = np.zeros((n, n))

print("Enter matrix A:")
for i in range(n):
    for j in range(n):
        A[i, j] = float(input(f"A[{i+1},{j+1}] = "))

# Augment A with identity matrix
aug = np.hstack((A, np.eye(n)))

# Gauss-Jordan elimination
for i in range(n):

    # Check zero pivot
    if aug[i, i] == 0:
        for k in range(i + 1, n):
            if aug[k, i] != 0:
                aug[[i, k]] = aug[[k, i]]
                break
        else:
            print("Inverse does not exist.")
            exit()

    # Make pivot = 1
    aug[i] = aug[i] / aug[i, i]

    # Make other elements in pivot column = 0
    for j in range(n):
        if i != j:
            m = aug[j, i]
            aug[j] = aug[j] - m * aug[i]

# Extract inverse
inverse = aug[:, n:]

print("\nInverse of A:")
print(inverse)

Enter order of matrix:  3


Enter matrix A:


A[1,1] =  2
A[1,2] =  1
A[1,3] =  3
A[2,1] =  4
A[2,2] =  5
A[2,3] =  6
A[3,1] =  7
A[3,2] =  8
A[3,3] =  9



Inverse of A:
[[ 0.33333333 -1.66666667  1.        ]
 [-0.66666667  0.33333333  0.        ]
 [ 0.33333333  1.         -0.66666667]]


In [ ]:
# SWEEP METHOD

n = int(input("Number of equations: "))

np.set_printoptions(precision=4, suppress=True)

# Input coefficient matrix A
A = np.zeros((n, n))

for i in range(n):
    for j in range(n):
        A[i, j] = float(input(f"Enter A{i+1}{j+1}: "))

print("\nCoefficient matrix A =")
print(A)

# Input matrix b
b = np.zeros((n, 1))

for i in range(n):
    b[i, 0] = float(input(f"Enter b{i+1}: "))

print("\nMatrix b =")
print(b)

# Create augmented matrix [A | b]
aug_mat = np.hstack([A, b])

print("\nAugmented matrix [A | b] =")
print(aug_mat)

# Sweep method
for k in range(n):

    # Pivoting
    if np.abs(aug_mat[k, k]) == 0.0:
        for i in range(k + 1, n):
            if aug_mat[i, k] != 0:
                aug_mat[[k, i], :] = aug_mat[[i, k], :]
                print("Row", k+1, "and row", i+1, "interchanged.")
                break

    # Make pivot element 1
    aug_mat[k, :] = aug_mat[k, :] / aug_mat[k, k]

    # Make other elements in pivot column zero
    for i in range(n):
        if i == k or aug_mat[i, k] == 0.0:
            continue

        aug_mat[i, :] = aug_mat[i, :] - aug_mat[i, k] * aug_mat[k, :]

    # Remove small numerical errors
    aug_mat[np.abs(aug_mat) < 1e-10] = 0

    print("\nAfter sweep", k+1, ":")
    print(aug_mat)

# Solution
x = aug_mat[:, n:]
print("\nSolution:")
print(x)

In [ ]:
# SWEEP METHOD WITH CONDITION CHECKS

def sweep(a,n,i):
    A=[[0]*(n+1)for i in range(n+1)]
    for j in range(1,n+1):
        if j != i:
            A[i][j] = a[i][j]/a[i][i]
    for k in range(1,n+1):
        if k != i:
            A[k][i] = -(a[k][i]/a[i][i])
    A[i][i] = 1/a[i][i]
    for k in range(1,n+1):
        for j in range(1,n+1):
            if k != i and j != i:
                A[k][j] = a[k][j] - (a[k][i]*a[i][j])/a[i][i]
    
    for k in range(1,n+1):
        for j in range(1,n+1):
            a[k][j] = A[k][j]
                
e=0.0001;row=0;col=0
n=int(input("Enter size of matrix A: "))
a=[[0]*(n+1)for i in range(n+1)]
#print(a)
b=[[0]*(n+1)for i in range(n+1)]

print("enter the elements of matrix A row-wise:")
for i in range(1,n+1):
    for j in range(1,n+1):
        aij=float(input("input aij:"))
        a[i][j]=aij
print(a)

ans=input("Is matrix A singular ? (y / n) : ") #'y' for yes, 'n' for 'no'
sym=0 # '0' for 'symmetric', '1' for 'non-symmetric'
for i in range(1,n+1):
    for j in range(1,n+1):
        b[i][j]=a[j][i]
for i in range(1,n+1):
    for j in range(1,n+1):
        if b[i][j]!=a[i][j]:
            sym=1
            break
if sym == 0:
    print("Matrix A is symmetric")
else:
    print("Matrix A is not symmetric")

for i in range(1,n+1):
    if ans == 'n' and sym == 0: # A is n.s. and symmetric
        if abs(a[i][i])< e:
            for k in range(i+1,n+1):
                if abs(a[k][k]) > e:
                    for l in range(1,n+1):
                        a[i][l],a[k][l]=a[k][l],a[i][l]
                    row=i;col=k
                    break
            sweep(a,n,col)
        else:
            sweep(a,n,i)
    elif ans == 'n' and sym == 1:# A is n.s. and non-symmetric
        if abs(a[i][i]) < e:
            for k in range(i+1,n+1):
                if abs(a[k][k]) > e:
                    sweep(a,n,k)
                    break
            if abs(a[i][i]) > e:
                sweep(a,n,i)
            i = i+1
        else:
            sweep(a,n,i)
    elif ans == 'y' and sym == 0:# A is singular and symmetric
        if abs(a[i][i]) > e:
            sweep(a,n,i)
        
    else: # A is singular and non-symmetric
        print("the method is not applicable.")
        sys.exit()

if ans == 'n' and sym == 0:
    for l in range(1,n+1):
        a[l][row],a[l][col] = a[l][col],a[l][row]
 
print("The inverse of A is:")
for i in range(1,n+1):
    for j in range(1,n+1):
        print(round(a[i][j],4),end='\t')
    print("\n")