In [ ]:
# core numeric libraries:

#Package is a collection of modules.

#Library is a collection of packages.

# NumPy is a library for the Python programming
# language, adding support for large,
# multi-dimensional arrays and matrices,
# along with a large collection of high-level
# mathematical functions to operate on these arrays
#---------------------------------------------

# A package is something you can import into
# your Python code. 
# It's a directory with __init__.py file in it,
# which you can import normally with import pckg
 
# A directory without __init__.py is just a normal
# OS directory completely unrelated to Python.
# It can contain files


In [1]:
import math
s=math.sqrt(25)
print(s)

5.0


In [3]:
import numpy
a=numpy.array([0,1,2,3])
print('array a:',a)

array a: [0 1 2 3]


In [4]:
from numpy import array
a=array([1,2,3])
print('array a=',a)

array a= [1 2 3]


In [2]:
from numpy import array
from math import sqrt
s=sqrt(25)
a=array([0,1,2,3])
print(s)
print(a)

5.0
[0 1 2 3]


In [3]:
import numpy as np
a=np.array([0,1,2,3])
print(a)

[0 1 2 3]


In [9]:
import numpy as np
a=np.array([0,1,2,3])
print("one-dimensional array a=",a)
print("type of a:",a.dtype)
a1= np.array([3,5,7])
print("array a1=",a1)
print("number of dimensions of array a=",a.ndim)
print("number of elements in each dimension of a=",a.shape)
# the output will be a tuple
print("length of array a=",len(a))
b=np.array([1.,2.,2.]) # b=array([1.0,2.0,2.0])
print("type of b:",b.dtype)
ch=np.array(['c1','c2'])
print("type of ch:",ch.dtype)

one-dimensional array a= [0 1 2 3]
type of a: int32
array a1= [3 5 7]
number of dimensions of array a= 1
number of elements in each dimension of a= (4,)
length of array a= 4
type of b: float64
type of ch: <U2


In [2]:
import numpy as np
a=np.array([[1,2,3],[3,4,5]]) # is a 2x3 array
#a=np.array([(1,2,3),(3,4,5)]) # alternate way 
print("two-dimensional array a=\n",a)
print("number of dimensions of array a=",a.ndim)
print("number of elements in each dimension of a=",a.shape)
# shape for 2-dim array is the size of both dimensions
print("length of array a=",len(a))
# length of 2-dim array is the size of the first dimension

two-dimensional array a=
 [[1 2 3]
 [3 4 5]]
number of dimensions of array a= 2
number of elements in each dimension of a= (2, 3)
length of array a= 2


In [3]:
a=np.array([[1,2],[3,4,5]])
print(a)
print("number of elements in each dimension of a=",a.shape)

[list([1, 2]) list([3, 4, 5])]
number of elements in each dimension of a= (2,)


C:\Users\admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


In [6]:
# to search for something in 'numpy' library
np.lookfor('create array')

Search results for 'create array'
---------------------------------
numpy.array
    Create an array.
numpy.memmap
    Create a memory-map to an array stored in a *binary* file on disk.
numpy.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.fromiter
    Create a new 1-dimensional array from an iterable object.
numpy.partition
    Return a partitioned copy of an array.
numpy.ctypeslib.as_array
    Create a numpy array from a ctypes array or POINTER.
numpy.ma.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.ma.make_mask
    Create a boolean mask from an array.
numpy.lib.Arrayterator
    Buffered iterator for big arrays.
numpy.ctypeslib.as_ctypes
    Create and return a ctypes object from a numpy array.  Actually
numpy.ma.mrecords.fromarrays
    Creates a mrecarray from a (flat) list of masked arrays.
numpy.ma.mvoid.__new__
    Create a new masked array from scratch.
numpy.ma.MaskedArray.__new__
    Create a 

In [6]:
#three-dimensional array
a3=np.array([[[1],[2]],[[3],[4]]])
print("three-dim array a3 is:\n",a3)
print("number of elements in each dimension of a3=",a3.shape)
# it is a 2x2x1 array


three-dim array a3 is:
 [[[1]
  [2]]

 [[3]
  [4]]]
number of elements in each dimension of a3= (2, 2, 1)


In [11]:
a3_1=np.array([[[1,1,2],[2,1,3]],[[3,3,1],[4,1,2]]])
print("three-dim array a3_1 is:\n",a3_1)
print("number of elements in each dimension of a3_1=",a3_1.shape)
# it is a 2x2x3 array
# print the first element of a3
print('elements in the first dimension of a3:\n',a3_1)

three-dim array a3_1 is:
 [[[1 1 2]
  [2 1 3]]

 [[3 3 1]
  [4 1 2]]]
number of elements in each dimension of a3_1= (2, 2, 3)
elements in the first dimension of a3:
 [[[1 1 2]
  [2 1 3]]

 [[3 3 1]
  [4 1 2]]]


In [12]:
# we can explicitly define data type
a4=np.ones((2,2))
print("array a4 is:\n",a4)
# this will create a two-dim array of size 2x2 
# whose all elements are 1 and type will be 'float' by default
print("type of a4 is:",a4.dtype)
a5=np.ones((2,3),dtype=int)
print("array a5 is:\n",a5)
print("type of a5 is:",a5.dtype)


array a4 is:
 [[1. 1.]
 [1. 1.]]
type of a4 is: float64
array a5 is:
 [[1 1 1]
 [1 1 1]]
type of a5 is: int32


In [15]:
a6=np.array([1+2j,3+4j])
print("array a6 is:",a6)
print("type of a6 is:",a6.dtype)
a7=np.array([True,False,False,True])
print("array a7 is:",a7)
print("type of a7 is:",a7.dtype)
a8=np.array(['name','xyz','student'])
print("array a8 is:",a8)
print("type of a8 is:",a8.dtype)
a9=np.array(['good','afternoon','everyone'])
print("array a9 is:",a9)
print("type of a9 is:",a9.dtype)

array a6 is: [1.+2.j 3.+4.j]
type of a6 is: complex128
array a7 is: [ True False False  True]
type of a7 is: bool
array a8 is: ['name' 'xyz' 'student']
type of a8 is: <U7
array a9 is: ['good' 'afternoon' 'everyone']
type of a9 is: <U9


In [17]:
help(np.arange)


Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : number, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : number
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off affects the length of `out`.
   

In [16]:
# indexing and slicing of array
b1=np.arange(10)
print("b1=",b1)
print("first element of b1 is:",b1[0])
print("last element of b1 is:",b1[-1])
print("second, third and second last elements are:",b1[1],b1[2],b1[-2])
print("alternate elements of b1 are:",b1[::2])
print("every third element, starting with second element of b1:",b1[1::3])
print("array b1 in reverse order:",b1[::-1])

b1= [0 1 2 3 4 5 6 7 8 9]
first element of b1 is: 0
last element of b1 is: 9
second, third and second last elements are: 1 2 8
alternate elements of b1 are: [0 2 4 6 8]
every third element, starting with second element of b1: [1 4 7]
array b1 in reverse order: [9 8 7 6 5 4 3 2 1 0]


In [14]:
B1=np.diag(np.array([3,6,9]))
print("B1 =\n",B1)
b1=np.arange(1,4)
print("b1=\n",b1)
B2=np.diag(np.arange(1,4))
print("B2=\n",B2)
B3=np.diag(np.arange(2,10,2))
print("B3=\n",B3)
b2=np.diag(np.arange(3))
print("b2=\n",b2)

B1 =
 [[3 0 0]
 [0 6 0]
 [0 0 9]]
b1=
 [1 2 3]
B2=
 [[1 0 0]
 [0 2 0]
 [0 0 3]]
B3=
 [[2 0 0 0]
 [0 4 0 0]
 [0 0 6 0]
 [0 0 0 8]]
b2=
 [[0 0 0]
 [0 1 0]
 [0 0 2]]


In [16]:
print("b2[1,1]=",b2[1,1])
print("b2[2,1]=",b2[2,1])
b2[2,1]=10 # changing the element of an array
print("now b2=\n",b2)
print("second row of b2=",b2[1])
print("third column of b2=",b2[:,2])
# partitioning 
print("the first and third row, & second and third column of b2:",b2[(0,2),1:3] ) 
print(b2[0:1,0:2])
print(b2[0:2,0:2])

b2[1,1]= 1
b2[2,1]= 10
now b2=
 [[ 0  0  0]
 [ 0  1  0]
 [ 0 10  2]]
second row of b2= [0 1 0]
third column of b2= [0 0 2]
the first and third row, & second and third column of b2: [[ 0  0]
 [10  2]]
[[0 0]]
[[0 0]
 [0 1]]


In [16]:
b3=np.arange(10) 
print("b3=",b3)                            
print("b3[5:]=",b3[5:])
b3[5:]=10
print("now b3 is:",b3)
b4=np.arange(5)
print("b4=",b4)
b3[5:]=b4[::-1]
print("now b3 is:",b3)     

b3= [0 1 2 3 4 5 6 7 8 9]
b3[5:]= [5 6 7 8 9]
now b3 is: [ 0  1  2  3  4 10 10 10 10 10]
b4= [0 1 2 3 4]
now b3 is: [0 1 2 3 4 4 3 2 1 0]


In [17]:
a=np.array([0,1,2])
a1=np.tile(a,2)
print("a1=",a1)
a2=np.tile(a,(2,2))
print("a2=",a2)
b=np.array([[1,2],[3,4]])
print("b=\n",b)
print(np.tile(b,2)) # same as print(np.tile(b,(1,2)))
print(np.tile(b,(2,1)))
print(np.tile(b,(2,2)))


a1= [0 1 2 0 1 2]
a2= [[0 1 2 0 1 2]
 [0 1 2 0 1 2]]
b=
 [[1 2]
 [3 4]]
[[1 2 1 2]
 [3 4 3 4]]
[[1 2]
 [3 4]
 [1 2]
 [3 4]]
[[1 2 1 2]
 [3 4 3 4]
 [1 2 1 2]
 [3 4 3 4]]


In [19]:
help(np.tile)

Help on function tile in module numpy:

tile(A, reps)
    Construct an array by repeating A the number of times given by reps.
    
    If `reps` has length ``d``, the result will have dimension of
    ``max(d, A.ndim)``.
    
    If ``A.ndim < d``, `A` is promoted to be d-dimensional by prepending new
    axes. So a shape (3,) array is promoted to (1, 3) for 2-D replication,
    or shape (1, 1, 3) for 3-D replication. If this is not the desired
    behavior, promote `A` to d-dimensions manually before calling this
    function.
    
    If ``A.ndim > d``, `reps` is promoted to `A`.ndim by pre-pending 1's to it.
    Thus for an `A` of shape (2, 3, 4, 5), a `reps` of (2, 2) is treated as
    (1, 1, 2, 2).
    
    Note : Although tile may be used for broadcasting, it is strongly
    recommended to use numpy's broadcasting operations and functions.
    
    Parameters
    ----------
    A : array_like
        The input array.
    reps : array_like
        The number of repetitions of `A`

In [23]:
# copying an array 
A1=np.arange(10)
A2=A1.copy()
# same as: A2=A1
A3=A1[::2].copy() # same as A3=A1[::2]
print("A1=",A1)
print("A2=",A2)
print("A3=",A3)

A1= [0 1 2 3 4 5 6 7 8 9]
A2= [0 1 2 3 4 5 6 7 8 9]
A3= [0 2 4 6 8]


In [21]:
A4=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("A4=",A4)
A5=A4[0:2,1:3]
print("A5=",A5)

A4= [[1 2 3]
 [4 5 6]
 [7 8 9]]
A5= [[2 3]
 [5 6]]


In [22]:
a2=np.linspace(0,1,6)
# it will generate 6 equally spaced points 
#starting from 0 and ending at 1 (spacing=(1-0)/(6-1))
# In general, spacing=(upper limit-lower limit)/(n-1)
# where n is the number of points required
print("a2=",a2)
a3=np.linspace(0,1,6,endpoint=False)
# spacing=(1-0)/6
# By default, endpoint=True
# when endpoint=False, spacing=(upper limit-lower limit)/n
print("a3=",a3)

a2= [0.  0.2 0.4 0.6 0.8 1. ]
a3= [0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333]


In [25]:
a=np.linspace(0,1,6)
print('a=',a)

a= [0.  0.2 0.4 0.6 0.8 1. ]


In [23]:
# Syntax: np.linspace(start, stop, num=50)

a4=np.linspace(0,1,5,endpoint=False)
print("a4=",a4)
a5=np.linspace(0,1,5)
print("a5=",a5)
a6=np.ones(3)
print("a6=",a6)
a7=np.ones((3,3))
print("a7=",a7)

a4= [0.  0.2 0.4 0.6 0.8]
a5= [0.   0.25 0.5  0.75 1.  ]
a6= [1. 1. 1.]
a7= [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [18]:
I=np.eye(3) # identity matrix of order 3
print("I=\n",I)

I=
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
b1=np.random.rand(4) 
# will generate an array of 4 uniform random numbers in range [0,1]
print("b1=",b1)
b2=np.random.randn(5)
# will genertate an array of 5 random numbers from N(0,1)
print("b2=",b2)
# we know, if X~N(mu,sigma), then z=(X-mu)/sigma ~ N(0,1)
# Then X = mu +sigma*z, where Z is a std normal
b3=2.5*np.random.randn(5)+3
# will generate an array of 5 random numbers from N(mean=3,sd=2.5)
print("b3=",b3)
b4=2.5*np.random.randn(2,4)+3
# will generate 2x4 array of random numbers from N(mean=3,sd=2.5)
print("b4=",b4)
b5=np.random.randint(0,21,10)
# will generate an array of 10 random numbers between 0 and 21
print("b5=",b5)

b1= [0.3271008  0.73179501 0.64882239 0.27273936]
b2= [-0.25895792  0.67141427  0.38024743  0.79086334 -0.48431492]
b3= [3.62584846 1.5606507  7.82201432 4.58933966 4.08518453]
b4= [[-2.74855663  3.11482345  2.99757886  1.37795022]
 [ 2.6201573   1.19799662  2.10235314  5.12935737]]
b5= [ 2  3 13 15  0  1  5 19 14 14]


In [26]:
# basic operations with array
# -------------------------------------
# Arithmetic and relational operations
print(b5%3==0)
# will create an array of logical values
print(b5[b5%3==0])
# will extract those elements of b5 which are
# evenly divisible by 3
b5[b5%3==0]=-1
# will replace those elements of b5 which are evenly
# divisible by 3, by -1
print("b5=",b5)
print(b5[[2,3,5,7]])
# will print elements with specified indices of b5 as an array

[ True  True False  True  True  True False  True False False]
[12  6  6  0 18 12]
b5= [-1 -1 17 -1 -1 -1  2 -1 17  4]
[17 -1 -1 -1]


In [27]:
a=array([1,2,3,4]) # same as a=np.array([1,2,3,4])
print(a+1)
print(2**a)
b=np.ones(4)+1
print("b=",b)
print(a-b)
a1=array([[1,2],[3,4]]) # same as a1=np.array()
print("a1=",a1)
b1=array([[2,3],[4,5]])
print("b1=",b1)
print("a1+b1=",a1+b1) # element-wise addition
add=np.add(a1,b1) # element-wise addition (same as a1+b1)
print("addition of a1 and b1=",add)
print("a1-b1=",a1-b1)  # element-wise subtraction
sub=np.subtract(a1,b1) # element-wise addition (same as (a1-b1))
print("element wise subtraction a1-b1=",sub)
print("element wise multiplication:",a1*b1) # OR USE - np.multiply(a1,b1)
# In element-wise multiplication, both arrays should be of same dimension
print("matrix multiplication:",a1.dot(b1)) # dot product, that is, usual matrix multiplication
print(a1/b1) # division , alternatively, np.divide(a1,b1)

[2 3 4 5]
[ 2  4  8 16]
b= [2. 2. 2. 2.]
[-1.  0.  1.  2.]
a1= [[1 2]
 [3 4]]
b1= [[2 3]
 [4 5]]
a1+b1= [[3 5]
 [7 9]]
addition of a1 and b1= [[3 5]
 [7 9]]
a1-b1= [[-1 -1]
 [-1 -1]]
element wise subtraction a1-b1= [[-1 -1]
 [-1 -1]]
element wise multiplication: [[ 2  6]
 [12 20]]
matrix multiplication: [[10 13]
 [22 29]]
[[0.5        0.66666667]
 [0.75       0.8       ]]


In [4]:
# use of relational operators
import numpy as np
c1=np.array([1,2,3])
c2=np.array([2,3,3])
print(c1==c2)
# The above code will do element-wise comparison and return T / F 
# corresponding to each element
#c3=array([2,3,3,1])
#print(c1==c3) # will be an error because of unequal length

print(c1>c2) # element-wise comparison
# print(c1<c3) will be an error because of unequal length

print(np.array_equal(c1,c2)) # will return True or False, only one value
# as a final answer, not element-wise comparison

c4=np.array([3,1,2])

print(np.array_equal(c1,c4))
c5=np.array([1,2,3])
print(np.array_equal(c1,c5))


[False False  True]
[False False False]
False
False
True


In [5]:
# logical operations
d1=np.array([True,False,True,False])
d2=np.array([False,False,True,True])
print(np.logical_or(d1,d2))
print(np.logical_and(d1,d2))
print(np.logical_not(d1))
d3=np.array([5>4,10<2])
d4=np.array([9%3,10%4])
print(d3)
print(d4)
print(np.logical_or(d3,d4))
print(np.logical_and(d3,d4))
print(np.logical_not(d3))

[ True False  True  True]
[False False  True False]
[False  True False  True]
[ True False]
[0 2]
[ True  True]
[False False]
[False  True]


In [30]:
# other mathematical functions
x=array([5,6.2,4.3])
print(np.sin(x))
print(np.log(x)) # natural log
print(np.log10(x)) # log base 10
print(np.exp(x))

[-0.95892427 -0.0830894  -0.91616594]
[1.60943791 1.82454929 1.45861502]
[0.69897    0.79239169 0.63346846]
[148.4131591  492.74904109  73.6997937 ]
