# Universal functions

## Vectorized operations

### Arithmetic operations 

Arithmetic operations on numpy arrays are vectorized. By vectorized, we mean, Arithmetic operations between ***equal-shaped*** arrays are carried out elementwise.  

In [1]:
import numpy as np
A = np.random.random(4).reshape(2, 2)        # random function generates random numbers from uniform (0, 1) distribution

In [2]:
B = np.array([[1, 2], [3, 4]])
B

array([[1, 2],
       [3, 4]])

In [3]:
A+B

array([[1.841487  , 2.80193665],
       [3.84360751, 4.56185699]])

In [4]:
A-B

array([[-0.158513  , -1.19806335],
       [-2.15639249, -3.43814301]])

In [5]:
A*B

array([[0.841487  , 1.60387329],
       [2.53082253, 2.24742797]])

Its important to understand that the last expression `A*B` doesn't result in matrix multiplication. It computes element-wise multiplications of the corresponding elements of `A` and `B`.  

It is clear that for arithmetic operations to be performed, both the operands must be the arrays of equal shape.  

Arithmetic operations, however, can also be performed on arrays of unequal shapes using broadcasting technique.

In [6]:
B

array([[1, 2],
       [3, 4]])

In [7]:
B+1

array([[2, 3],
       [4, 5]])

In [8]:
B*2

array([[2, 4],
       [6, 8]])

In above examples, the scalar 1 is broadcasted to shape (2, 2) with all elements 1 before performing the arithmetic.
Similarly, the scalar 2 is broadcasted to shape (2, 2) with all elements 2 before performing the arithmetic.

In [9]:
b = np.array([10, 20])
A+b

array([[10.841487  , 20.80193665],
       [10.84360751, 20.56185699]])

Note that 10 is added in each element of the first column, and 20 is added in each element of second column.
We can also add row-wise as shown below.

In [10]:
c = b[:,np.newaxis]
c

array([[10],
       [20]])

In [11]:
A+c

array([[10.841487  , 10.80193665],
       [20.84360751, 20.56185699]])

## Universal Functions

Universal Functions are the numpy functions that operate element wise on the ndarrays. Universal functions are numpy `ufunc` objects. 

### Unary universal functions

Many universal functions are element wise transformations. These functions take only one argument. Such functions are called unary ufuncs. For example,  

`np.sqrt`, `np.exp`, …  

In [12]:
x = np.array([1.2, 11.2, 9.6, 12.5, 17.5])
np.log(x) 


array([0.18232156, 2.41591378, 2.2617631 , 2.52572864, 2.86220088])

In [13]:
np.exp(x)

array([3.32011692e+00, 7.31304418e+04, 1.47647816e+04, 2.68337287e+05,
       3.98247844e+07])

In [14]:
type(np.exp)

numpy.ufunc

The last result shows that a universal functions is a `ufunc` object of numpy. 

### Binary universal functions

Some universal functions take two arrays as arguments and return single array as the result, by performing the binary function of the pairs of the corresponding elements of the two arrays. Such functions are called binary ufuncs.  

For example,

`np.maximum`, `np.add`, … 

In [15]:
a = np.array([10, 20, 30, 40, 50])
np.add(a, x)

array([11.2, 31.2, 39.6, 52.5, 67.5])

In [16]:
a + x

array([11.2, 31.2, 39.6, 52.5, 67.5])

The same results of the last two expressions above are obvious. This is because the `np.add` function is implicitely called while evaluating the `+` operator when at least one of the operand is an array. Thus, the expression `a + x` is in fact a syntactic sugar for the function call `np.add (a, x)`

All operators implicitely call corresponding universal functions when at least one of the operand is an array.  

For other arithmatic operators also corresponding universal functions are available. These ufunc's are 

`np.subtract`, `np.multiply`, `np.divide`, `np.power`, `np.floor_divide`, `np.remainder`, ...

In [17]:
b = np.array([5, 25, 32, 27, 39])
np.maximum (a, b)

array([10, 25, 32, 40, 50])

In [18]:
a>b

array([ True, False, False,  True,  True])

**Home Work:** Find out the available universal functions.

## Broadcasting

For universal functions taking multiple arrays as input, standard *broadcasting rules* are applied so that inputs of different shapes can still be usefully operated on. 

Broadcasting can be understood by four rules:

1. **Achieve common `ndim`** :   
   All input arrays with `ndim` smaller than the input array of largest `ndim`, have 1’s prepended to their shapes.
2. **Determine Shape of output array** :  
   The size in each dimension of the output shape is the maximum of all the input sizes in that dimension.
3. **Participation of elements in calculation** :  
   An input can be used in the calculation if its size in a particular dimension either matches the output size in that dimension, or has value exactly 1.
4. **Achieve common Shape** :  
   If an input has a dimension size of 1 in its shape, the only values in that dimension will be used for all calculations (i.e. *broadcasted*) along that dimension. In other words, the stepping machinery of the ufunc will simply not step along that dimension (i.e. the stride will be 0 for that dimension).

A set of arrays is said to be broadcastable to the same shape if one of the following is true:  

1. The arrays all have exactly the same shape.
2. The arrays all have the same number of dimensions and the length of each dimensions is either a common length or 1.
3. The arrays that have too few dimensions can have their shapes prepended with a dimension of length 1 to satisfy property 2.


### Example 1


In [19]:
x = np.array([2, 4, 6])
x+5

array([ 7,  9, 11])

#### Explanation:

Rule 1:	Here, the scalar 5, whose ndim is 0, is transformed into an array with ndim 1, and shape (1,) to match the ndim of x  
Rule 2: The shape of the output is (3,) as max(3, 1) = 3   
Rule 3: Although the shape (1,) doesn’t match with shape (3,), since the shape is 1, corresponding input can be used in the calculation  
Rule 4:	The first value 5 is used for all calculations along that dimension.  


### Example2:


In [20]:
a = np.array([[1, 2, 3], [1, 3, 2], [2, 1, 3]])
b = np.array([2, 1, 0])
a + b

array([[3, 3, 3],
       [3, 4, 2],
       [4, 2, 3]])

#### Explanation:  

Rule 1:	Here, the array b, whose ndim is 1 and shape (3, ), is transformed into an array with ndim 2  and shape (1, 3) to match the ndim of a.  
Rule 2: The shape of the output is (3, 3)  
Rule 3: Although the shape (1, 3) doesn’t match with shape (3, 3), since the size in the first dimension of b is 1, corresponding input can be used in the calculation  
Rule 4:	The first values 2, 1, and 0 in the second dimension are used for all calculations along the first dimension.  


====== Examples discussed during the session ==========

In [21]:
import math 
xx = np.array([1, 4, 9])
np.sqrt(xx)

array([1., 2., 3.])

In [22]:
type(math.sqrt)

builtin_function_or_method

In [23]:
type(np.sqrt)

numpy.ufunc