In [1]:
import numpy as np
x = np.array([5, 10, 15, 20])
a = np.array([[2, 4, 6], [20, 40, 60], [200, 400, 600]])


In [2]:
x

array([ 5, 10, 15, 20])

In [3]:
a

array([[  2,   4,   6],
       [ 20,  40,  60],
       [200, 400, 600]])

In [4]:
x.tolist()

[5, 10, 15, 20]

In [5]:
a.tolist()

[[2, 4, 6], [20, 40, 60], [200, 400, 600]]

In [6]:
x.tofile?

In [9]:
x.tofile("e:\\xdata.out",",")
a.tofile("e:\\adata.out",",")

In [10]:
y = x.copy()
z = x.view()

In [11]:
y

array([ 5, 10, 15, 20])

In [12]:
z

array([ 5, 10, 15, 20])

In [13]:
y[1] = 6


In [14]:
x

array([ 5, 10, 15, 20])

In [15]:
y

array([ 5,  6, 15, 20])

In [16]:
z[1] = 7

In [17]:
x

array([ 5,  7, 15, 20])

In [18]:
z

array([ 5,  7, 15, 20])

In [19]:
x.resize((2, 2))

In [20]:
x

array([[ 5,  7],
       [15, 20]])

In [21]:
x.reshape((4,))

array([ 5,  7, 15, 20])

In [22]:
x

array([[ 5,  7],
       [15, 20]])

In [23]:
x.transpose()

array([[ 5, 15],
       [ 7, 20]])

In [7]:
b = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
              [[10, 20, 30], [40, 50, 60], [70, 80, 90]]
             ])

In [8]:
b

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]]])

In [9]:
b[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
b[1]

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [11]:
b[0, 0]

array([1, 2, 3])

In [12]:
b[0, 1]

array([4, 5, 6])

In [13]:
b[1, 0]

array([10, 20, 30])

In [14]:
b

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]]])

In [15]:
b.transpose((0, 1, 2))

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]]])

In [20]:
b.transpose((0, 2, 1))

array([[[ 1,  4,  7],
        [ 2,  5,  8],
        [ 3,  6,  9]],

       [[10, 40, 70],
        [20, 50, 80],
        [30, 60, 90]]])

In [21]:
b.transpose(1, 2, 0)

array([[[ 1, 10],
        [ 2, 20],
        [ 3, 30]],

       [[ 4, 40],
        [ 5, 50],
        [ 6, 60]],

       [[ 7, 70],
        [ 8, 80],
        [ 9, 90]]])

In [22]:
y = np.array([5, 2, 9, 6, 11])

In [23]:
y.sort()

In [24]:
y

array([ 2,  5,  6,  9, 11])

In [25]:
y

array([ 2,  5,  6,  9, 11])

In [26]:
sid = y.argsort()

In [27]:
y[sid[0]]

2

In [28]:
y[sid[1]]

5

In [29]:
x

array([ 5, 10, 15, 20])

In [30]:
x.partition?

In [31]:
y

array([ 2,  5,  6,  9, 11])

In [32]:
y.partition(2)

In [33]:
y

array([ 2,  5,  6,  9, 11])

In [34]:
y

array([ 2,  5,  6,  9, 11])

In [35]:
y.partition(3)

In [36]:
y

array([ 5,  2,  6,  9, 11])

In [37]:
y.ptp()

9

In [38]:
a

array([[  2,   4,   6],
       [ 20,  40,  60],
       [200, 400, 600]])

In [39]:
a.data

In [60]:
b = np.loadtxt("e:\\somedata.txt")

In [61]:
b

array([11., 12., 13., 14., 15., 16., 17., 18., 19., 20.])

In [62]:
c = np.loadtxt("e:\\data2.txt")

In [63]:
c

array([[  1.,   2.,   3.],
       [ 11.,  22.,  33.],
       [111., 222., 333.]])

In [64]:
f = open("e:\\data3.txt")
d = np.loadtxt(f)

In [65]:
d

array([[  1. ,   2. ,   3. ],
       [ 11. ,  22. ,  33. ],
       [111. , 222. , 333. ],
       [  1.5,   2.5,   3.5]])