# Numpy Package

## Creating a numpy array

In [1]:
import numpy as np         # np is the standard alias for numpy 
data = [6, 7.5, 8, 0, 1]   # Python list object
x = np.array(data)         # Using arry function of numpy

Above statements have created a one-dimentional numpy arry x.

In [2]:
another_data = [[1, 2, 3, 4], [5, 6, 7, 8]]
y = np.array(another_data)

These statements have created a two-dimentional numpy arry x.  
The type of object is `numpy.ndarray` as shown below.

In [3]:
type(x)

numpy.ndarray

In [4]:
type(y)

numpy.ndarray

### Attributes of numpy array  

##### dtype
The dtype attribute returns the common data type of the array elements.  

In [5]:
x.dtype

dtype('float64')

In [6]:
y.dtype

dtype('int32')

Note that these dtypes have been chosen automatically by the array function.  
It is also possible explicitly specify the dtype while creating an ndarray.This is shown below.

In [7]:
x1 = np.array(data, dtype = 'float32')
x1.dtype

dtype('float32')

#### ndim  
The ndim attribute returns the number of dimensions of an array.

In [8]:
x.ndim

1

In [9]:
y.ndim

2

#### shape

Shape of an ndarray is a tuple that specify size of each dimension.

In [10]:
x.shape

(5,)

In [11]:
y.shape

(2, 4)

#### size
Size of an ndarray is the number of elements in array

In [12]:
print(x)
x.size

[6.  7.5 8.  0.  1. ]


5

In [13]:
print(y)
y.size

[[1 2 3 4]
 [5 6 7 8]]


8

#### itemsize
Item size returns the size of an array elements in bytes

In [14]:
x.itemsize   # Recall that dtype of x is float64

8

In [15]:
x1.itemsize  # dtype is float32

4

In [16]:
y.itemsize  # dtype is int32

4

### Array Scalars
When a specific element of an array is extracted by *indexing the array*, the extracted element is an array scalar.

In [17]:
a = x[2]
type(a)

numpy.float64

Arry scalars supports the same methods and attributes as ndarrays.

In [18]:
a.ndim

0

## Different ways of creating numpy arrays
### Using other python structures

1. Using other Python structures

We have already seen how to create an ndarray using `array` function of numpy using List as argument.

2. Using built-in numpy functions

There are a number of other functions also for creating new arrays.


In [19]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [20]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [21]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [23]:
np.arange(2, 1, -0.1)

array([2. , 1.9, 1.8, 1.7, 1.6, 1.5, 1.4, 1.3, 1.2, 1.1])

In [24]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
np.empty(7)

array([0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 3.44897822e-307])