# Indexing Numpy Array

In [1]:
import numpy as np
a = np.array([12, 34, 32, 56, 33])

In [2]:
a

array([12, 34, 32, 56, 33])

## Positive integer as index

In [3]:
a[0]         # 0th element - element with index 0

12

In [4]:
a[2]         # Element with index 2

32

In [5]:
i = 3
a[i]         # variable as an index, variable must take integer value

56

In [6]:
a[i-2]       # Expression as an index

34

In [7]:
i/2

1.5

In [8]:
a[i/2]       # expression with non-integer value not allowed

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [9]:
s = a[i+1]*2     # indexed array element can participate in an expression

In [10]:
s

66

## Negative integer as index

In [11]:
a[-1]      # refers to 1st value from end

33

In [12]:
a[-2]      # 2nd value from end

56

### Index value must be within the bounds

In [13]:
a[5]

IndexError: index 5 is out of bounds for axis 0 with size 5

This is a runtime error, called **exception**. The name of the exception is `IndexError`.  
Also note that the only dimension of the one-dimensional array a is refered to as `axis 0` in the message.

In [14]:
## Bool array as index

In [15]:
even = a%2 == 0     # even is a bool array (of the same size as a)

In [16]:
even

array([ True,  True,  True,  True, False])

In [17]:
a[even]        # The elements corresponding to "True" in the index array are extracted.

array([12, 34, 32, 56])

In [18]:
a[2]=23

In [19]:
a

array([12, 34, 23, 56, 33])

In [20]:
a[a%2==1]

array([23, 33])

In [21]:
gender = np.array(['Male', 'Male', 'Female', 'Male', 'Female'])

In [22]:
gender

array(['Male', 'Male', 'Female', 'Male', 'Female'], dtype='<U6')

In [23]:
gender=='Male'

array([ True,  True, False,  True, False])

In [24]:
a[gender=='Male']     # Values in a corresponding to Male gender

array([12, 34, 56])

## Indexing a 2d array

In [25]:
b = np.array([[1, 2, 3, 4, 5], [11, 22, 33, 44, 55]])

In [26]:
b

array([[ 1,  2,  3,  4,  5],
       [11, 22, 33, 44, 55]])

In [27]:
b.shape

(2, 5)

In [28]:
b[0, 0]

1

In [29]:
b[0, 2]

3

In [30]:
b[1, 3]      # index value 1 for "axis 0", and index value 3 for "axis 1"

44

In [31]:
b[0, -1]     # -ve value as index have the same meaning as discussed earlier

5

In [32]:
b > 10

array([[False, False, False, False, False],
       [ True,  True,  True,  True,  True]])

In [33]:
b[b>10]     # bool array of the same shape as b can be used as an index for b

array([11, 22, 33, 44, 55])

In [34]:
b

array([[ 1,  2,  3,  4,  5],
       [11, 22, 33, 44, 55]])

## Using less number of indices than ndim

In [35]:
b[0]    # Referes to entire row with index 0

array([1, 2, 3, 4, 5])

In [36]:
b[1]    # Row with index 1

array([11, 22, 33, 44, 55])

## Slicing

In [37]:
a

array([12, 34, 23, 56, 33])

In [38]:
a[:3]        # All elements upto, but excluding, index 3

array([12, 34, 23])

In [39]:
a[2:]        # All elements with index 2 and above

array([23, 56, 33])

In [40]:
a[2:5]       # All elements with index 2 or more but less than 5

array([23, 56, 33])

In [44]:
a

array([12, 34, 23, 56, 33])

In [41]:
a[1:5]

array([34, 23, 56, 33])

In [42]:
a[1:5:2]    # step size can be optionally specified for index update

array([34, 56])

In [43]:
a[4:1:-1]   # -ve stepsize can also be used

array([33, 56, 23])

In [46]:
b

array([[ 1,  2,  3,  4,  5],
       [11, 22, 33, 44, 55]])

In [45]:
b[0,2:5]   # Slicing can be used for any axis (i.e. dimension)

array([3, 4, 5])

In [46]:
b[:2, 2:4]  # Slicing can also be used for both the axes.

array([[ 3,  4],
       [33, 44]])

In [47]:
a

array([12, 34, 23, 56, 33])

In [48]:
a[:]     # Only ':' character means all index values, from begining to end

array([12, 34, 23, 56, 33])

In [49]:
b

array([[ 1,  2,  3,  4,  5],
       [11, 22, 33, 44, 55]])

In [50]:
b[:,3]      # Referes to column with index 3

array([ 4, 44])

In [51]:
b[0,:]      # Same as b[0]. Thus, ':' is optional for one or more axes at the end

array([1, 2, 3, 4, 5])

In [52]:
b[0]

array([1, 2, 3, 4, 5])