# Numpy Package

## Creating a numpy array

In [1]:
import numpy as np         # np is the standard alias for numpy 
data = [6, 7.5, 8, 0, 1]   # Python list object
x = np.array(data)         # Using arry function of numpy

Above statements have created a one-dimentional numpy arry x.

In [2]:
another_data = [[1, 2, 3, 4], [5, 6, 7, 8]]
y = np.array(another_data)

These statements have created a two-dimentional numpy arry x.  
The type of object is `numpy.ndarray` as shown below.

In [3]:
type(x)

numpy.ndarray

In [4]:
type(y)

numpy.ndarray

### Attributes of numpy array  

##### dtype
The dtype attribute returns the common data type of the array elements.  

In [5]:
x.dtype

dtype('float64')

In [6]:
y.dtype

dtype('int32')

Note that these dtypes have been chosen automatically by the array function.  
It is also possible explicitly specify the dtype while creating an ndarray.This is shown below.

In [7]:
x1 = np.array(data, dtype = 'float32')
x1.dtype

dtype('float32')

#### ndim  
The ndim attribute returns the number of dimensions of an array.

In [8]:
x.ndim

1

In [9]:
y.ndim

2

#### shape

Shape of an ndarray is a tuple that specify size of each dimension.

In [10]:
x.shape

(5,)

In [11]:
y.shape

(2, 4)

#### size
Size of an ndarray is the number of elements in array

In [12]:
print(x)
x.size

[6.  7.5 8.  0.  1. ]


5

In [13]:
print(y)
y.size

[[1 2 3 4]
 [5 6 7 8]]


8

#### itemsize
Item size returns the size of an array elements in bytes

In [14]:
x.itemsize   # Recall that dtype of x is float64

8

In [15]:
x1.itemsize  # dtype is float32

4

In [16]:
y.itemsize  # dtype is int32

4

### Array Scalars
When a specific element of an array is extracted by *indexing the array*, the extracted element is an array scalar.

In [17]:
a = x[2]
type(a)

numpy.float64

Arry scalars supports the same methods and attributes as ndarrays.

In [18]:
a.ndim

0

## Different ways of creating numpy arrays
### Using other python structures

1. Using other Python structures

We have already seen how to create an ndarray using `array` function of numpy using List as argument.

2. Using built-in numpy functions

There are a number of other functions also for creating new arrays.


In [19]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [20]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [21]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [23]:
np.arange(2, 1, -0.1)

array([2. , 1.9, 1.8, 1.7, 1.6, 1.5, 1.4, 1.3, 1.2, 1.1])

In [24]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
np.empty(7)

array([0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 2.24045285e+243])

## Indexing numpy array

Numpy ndarrays can be indexed using the standard syntax `x[obj]`, where x is the array and obj the selection. Two kinds of indexing are available: 
* Basic indexing
  * Field access 
  * Slicing 
* Advanced indexing 
  * Using bool array as index
  * Fancy indexing (Using non-bool array as index)

The type of `obj` determines the kind of indexing being used.  

From the syntax specified above, it may appear that multidimensional indexing such as `x[2, 3]` doesnot follow the syntax. However, following examples clarifies that expression such as `x[i, j]` is actually same as `x[(i, j)]`, where the index is a tuple.

In [26]:
a = np.array([11, 22, 33, 44, 55])
b = np.array([[1.1, 2.2, 3.3, 4.4, 5.5],
              [11.1, 22.2, 33.3, 44.4, 55.5],
              [1.11, 2.22, 3.33, 4.44, 5.55]])

In [27]:
b[(2, 3)]

4.44

In [28]:
b[2, 3]

4.44

Thus, `b[expr1, expr2]` is actually a *syntactic sugar* for `b[(expr1, expr2)]`

### Slicing

Slicing operation of core python is supported in numpy also, but for n dimensions.

To perform slicing, use ***slice object*** (or tuple of slice objects) as index. A slice object is constructed by syntax `start:end[:step]`

In [29]:
a[:3]

array([11, 22, 33])

In [30]:
a[2:]

array([33, 44, 55])

In [31]:
a[1:4]

array([22, 33, 44])

In [32]:
b[:2]

array([[ 1.1,  2.2,  3.3,  4.4,  5.5],
       [11.1, 22.2, 33.3, 44.4, 55.5]])

In [33]:
b[:,:3]

array([[ 1.1 ,  2.2 ,  3.3 ],
       [11.1 , 22.2 , 33.3 ],
       [ 1.11,  2.22,  3.33]])

In [34]:
b[1:3, 2:4]

array([[33.3 , 44.4 ],
       [ 3.33,  4.44]])

It is important to note that the slicing operation preserves the dimension of array. Whereas normal indexing collapses the array to a lower dimensional arry.  

See, for example, the following results.

In [35]:
b[1, 1:4]       # Results in 1-d array.

array([22.2, 33.3, 44.4])

In [36]:
b[1:2, 1:4]    # Results in 2-d array

array([[22.2, 33.3, 44.4]])

In [37]:
b[:2, 3]      # Results in 1-d array

array([ 4.4, 44.4])

In [38]:
b[:2, 3:4]      # Results in 2-d array

array([[ 4.4],
       [44.4]])

### Fancy Indexing

Fancy indexing is performed when an array (or tuple of arrays) of integers is used as index.  

#### Fancy indexing 1-d array

In [39]:
a

array([11, 22, 33, 44, 55])

In [40]:
a[[0, 2, 3]]             # List will be treated as 1-d array when used as index

array([11, 33, 44])

In [41]:
a[np.array([0, 2, 3])]   # Same result

array([11, 33, 44])

In [42]:
a[[1, 2, 2]]

array([22, 33, 33])

In [43]:
a[np.array([[0, 2],[1, 3]])]

array([[11, 33],
       [22, 44]])

In [44]:
a[np.array([[0],[3]])]

array([[11],
       [44]])

It important to note that **the shape of the result is same as the shape of index**.

#### Fancy indexing 2-d array

In [45]:
b

array([[ 1.1 ,  2.2 ,  3.3 ,  4.4 ,  5.5 ],
       [11.1 , 22.2 , 33.3 , 44.4 , 55.5 ],
       [ 1.11,  2.22,  3.33,  4.44,  5.55]])

In [46]:
b[([0,2], [1, 3])]     

array([2.2 , 4.44])

In [47]:
b[[0,2], [1, 3]]     # Using the syntactic sugar

array([2.2 , 4.44])

The result is surprising, as most people will expect that a matrix will be returned comprising of two rows and two columns. Instead the result is a 1-d array containing (0,1)th element and (2, 3)th element.

In general, for the fancy indexing of an n-dimensional array, all n indices must be the arrays of the same shape, and the result of such indexing is also of the same shape.

In [48]:
b[np.array([[0],[2]]), np.array([[1],[3]])]         # both indices have shape (2,1)

array([[2.2 ],
       [4.44]])

In [49]:
id1 = np.array([[0,0],[2, 2]])
id1

array([[0, 0],
       [2, 2]])

In [50]:
id2 = np.array([[1, 2], [1, 2]])
id2

array([[1, 2],
       [1, 2]])

In [ ]:
b[id1, id2]