# Working with numpy Arrays

## Indexing numpy array

Numpy ndarrays can be indexed using the standard syntax `x[obj]`, where x is the array and obj the selection. Two kinds of indexing are available: 
* Basic indexing
  * Field access 
  * Slicing 
* Advanced indexing 
  * Using bool array as index
  * Fancy indexing (Using non-bool array as index)

The type of `obj` determines the kind of indexing being used.  

From the syntax specified above, it may appear that multidimensional indexing such as `x[2, 3]` doesnot follow the syntax. However, following examples clarifies that expression such as `x[i, j]` is actually same as `x[(i, j)]`, where the index is a tuple.

In [1]:
import numpy as np
a = np.array([11, 22, 33, 44, 55])
b = np.array([[1.1, 2.2, 3.3, 4.4, 5.5],
              [11.1, 22.2, 33.3, 44.4, 55.5],
              [1.11, 2.22, 3.33, 4.44, 5.55]])

In [2]:
b[(2, 3)]

4.44

In [3]:
b[2, 3]

4.44

Thus, `b[expr1, expr2]` is actually a *syntactic sugar* for `b[(expr1, expr2)]`

### Slicing

Slicing operation of core python is supported in numpy also, but for n dimensions.

To perform slicing, use ***slice object*** (or tuple of slice objects) as index. A slice object is constructed by syntax `start:end[:step]`

In [4]:
a[:3]

array([11, 22, 33])

In [5]:
a[2:]

array([33, 44, 55])

In [6]:
a[1:4]

array([22, 33, 44])

In [7]:
b[:2]

array([[ 1.1,  2.2,  3.3,  4.4,  5.5],
       [11.1, 22.2, 33.3, 44.4, 55.5]])

In [8]:
b[:,:3]

array([[ 1.1 ,  2.2 ,  3.3 ],
       [11.1 , 22.2 , 33.3 ],
       [ 1.11,  2.22,  3.33]])

In [9]:
b[1:3, 2:4]

array([[33.3 , 44.4 ],
       [ 3.33,  4.44]])

It is important to note that the slicing operation preserves the dimension of array. Whereas normal indexing collapses the array to a lower dimensional arry.  

See, for example, the following results.

In [10]:
b[1, 1:4]       # Results in 1-d array.

array([22.2, 33.3, 44.4])

In [11]:
b[1:2, 1:4]    # Results in 2-d array

array([[22.2, 33.3, 44.4]])

In [12]:
b[:2, 3]      # Results in 1-d array

array([ 4.4, 44.4])

In [13]:
b[:2, 3:4]      # Results in 2-d array

array([[ 4.4],
       [44.4]])

### Fancy Indexing

Fancy indexing is performed when an array (or tuple of arrays) of integers is used as index.  

#### Fancy indexing 1-d array

In [14]:
a

array([11, 22, 33, 44, 55])

In [15]:
a[[0, 2, 3]]             # List will be treated as 1-d array when used as index

array([11, 33, 44])

In [16]:
a[np.array([0, 2, 3])]   # Same result

array([11, 33, 44])

In [17]:
a[[1, 2, 2]]

array([22, 33, 33])

In [18]:
a[np.array([[0, 2],[1, 3]])]

array([[11, 33],
       [22, 44]])

In [19]:
a[np.array([[0],[3]])]

array([[11],
       [44]])

It important to note that **the shape of the result is same as the shape of index**.

#### Fancy indexing 2-d array

In [20]:
b

array([[ 1.1 ,  2.2 ,  3.3 ,  4.4 ,  5.5 ],
       [11.1 , 22.2 , 33.3 , 44.4 , 55.5 ],
       [ 1.11,  2.22,  3.33,  4.44,  5.55]])

In [21]:
b[([0,2], [1, 3])]     

array([2.2 , 4.44])

In [22]:
b[[0,2], [1, 3]]     # Using the syntactic sugar

array([2.2 , 4.44])

The result is surprising, as most people will expect that a matrix will be returned comprising of two rows and two columns. Instead the result is a 1-d array containing (0,1)th element and (2, 3)th element.

In general, for the fancy indexing of an n-dimensional array, all n indices must be the arrays of the same shape, and the result of such indexing is also of the same shape.

In [23]:
b[np.array([[0],[2]]), np.array([[1],[3]])]         # both indices have shape (2,1)

array([[2.2 ],
       [4.44]])

In [24]:
id1 = np.array([[0,0],[2, 2]])
id1

array([[0, 0],
       [2, 2]])

In [25]:
id2 = np.array([[1, 2], [1, 2]])
id2

array([[1, 2],
       [1, 2]])

In [26]:
b[id1, id2]

array([[2.2 , 3.3 ],
       [2.22, 3.33]])

in above example, both the indices id1 and id2 are 2-d arrays of shape (2,2). Therefore, 
the result is also a 2-d array of shape(2,2), comprising of the index pairs formed by the corresponding elements of the two 
indices id1 and id2.  

This examples, also shows how to obtain the submatrix (subarray) comprising of rows indexed by 0 and 2, and the columns indexed by 1, and 2.

Following example shows an alternative way of achieving the same result.

In [27]:
id1 = np.array([[0], [2]])
id1

array([[0],
       [2]])

In [28]:
id2 = [1, 2]
id2

[1, 2]

In [29]:
b[id1, id2]

array([[2.2 , 3.3 ],
       [2.22, 3.33]])

This example works due to the mechanism of ***broadcasting***. Broadcasting will be discussed later.  

`np.ix_` function provides a simpler way of achieving the same result as above.

In [30]:
b[np.ix_([0,2],[1,2])]

array([[2.2 , 3.3 ],
       [2.22, 3.33]])

Function `np.ix_` evaluates to a tuple of arrays of the requires shapes.

In [31]:
np.ix_([0,2],[1,2])

(array([[0],
        [2]]),
 array([[1, 2]]))

#### Mixing the types of indexing

In [32]:
b

array([[ 1.1 ,  2.2 ,  3.3 ,  4.4 ,  5.5 ],
       [11.1 , 22.2 , 33.3 , 44.4 , 55.5 ],
       [ 1.11,  2.22,  3.33,  4.44,  5.55]])

In [33]:
b[1, 2:4]

array([33.3, 44.4])

In [34]:
b[1, [2, 4]]

array([33.3, 55.5])

In [35]:
b[[1], :]

array([[11.1, 22.2, 33.3, 44.4, 55.5]])

In [36]:
b[[0,2],:]

array([[1.1 , 2.2 , 3.3 , 4.4 , 5.5 ],
       [1.11, 2.22, 3.33, 4.44, 5.55]])

In [37]:
b[:,[2, 4]]

array([[ 3.3 ,  5.5 ],
       [33.3 , 55.5 ],
       [ 3.33,  5.55]])

## Copy vs View

Basic indexing creates a view, whereas advanced indexing creates a copy. A view refers to the elements of original array, thereby preserving memory. As opposed to that copy is another array having the same value as original array.

### Modifying elements of array

In [38]:
a

array([11, 22, 33, 44, 55])

In [39]:
a[2] = 35
a

array([11, 22, 35, 44, 55])

In [40]:
a[:2]= [10, 20]
a

array([10, 20, 35, 44, 55])

Elements of an array can be modified by assigning as shown above.

In [41]:
a_part = a[1:4]     # a_part is a view
a_part

array([20, 35, 44])

In [42]:
a[1]=21
a_part

array([21, 35, 44])

Any change in a is also reflected in the view a_part. Similarly, a change in view changes the original array

In [43]:
a_part[0] = 25
a

array([10, 25, 35, 44, 55])

In [44]:
b

array([[ 1.1 ,  2.2 ,  3.3 ,  4.4 ,  5.5 ],
       [11.1 , 22.2 , 33.3 , 44.4 , 55.5 ],
       [ 1.11,  2.22,  3.33,  4.44,  5.55]])

In [45]:
row0 = b[0]       # row0 is a view
b[0,2] = 33.1
b

array([[ 1.1 ,  2.2 , 33.1 ,  4.4 ,  5.5 ],
       [11.1 , 22.2 , 33.3 , 44.4 , 55.5 ],
       [ 1.11,  2.22,  3.33,  4.44,  5.55]])

In [46]:
row0

array([ 1.1,  2.2, 33.1,  4.4,  5.5])

In [47]:
row0[:3] = [1.5, 2.5, 3.5]
row0

array([1.5, 2.5, 3.5, 4.4, 5.5])

In [48]:
b

array([[ 1.5 ,  2.5 ,  3.5 ,  4.4 ,  5.5 ],
       [11.1 , 22.2 , 33.3 , 44.4 , 55.5 ],
       [ 1.11,  2.22,  3.33,  4.44,  5.55]])

Note that any change in `b` is reflected in `row0` and vice-versa. This is because both refer to the same memory locations

In [49]:
row1 = b[[1]]        # row1 is a copy
row1

array([[11.1, 22.2, 33.3, 44.4, 55.5]])

In [50]:
b[1, 1] = 22.5
b

array([[ 1.5 ,  2.5 ,  3.5 ,  4.4 ,  5.5 ],
       [11.1 , 22.5 , 33.3 , 44.4 , 55.5 ],
       [ 1.11,  2.22,  3.33,  4.44,  5.55]])

In [51]:
row1

array([[11.1, 22.2, 33.3, 44.4, 55.5]])

Since `row1` is an independent array, change in `b` doesn't change `row1`

### Explicitly creating copy

`copy` method can be used to explicitly create a copy as shown below.

In [52]:
col12_view = b[:,1:3]
col12_copy = b[:,1:3].copy()

In [53]:
col12_view

array([[ 2.5 ,  3.5 ],
       [22.5 , 33.3 ],
       [ 2.22,  3.33]])

In [54]:
col12_copy

array([[ 2.5 ,  3.5 ],
       [22.5 , 33.3 ],
       [ 2.22,  3.33]])

In [55]:
b[0,2] = 3.6; b[1,2] = 33.6

In [56]:
b

array([[ 1.5 ,  2.5 ,  3.6 ,  4.4 ,  5.5 ],
       [11.1 , 22.5 , 33.6 , 44.4 , 55.5 ],
       [ 1.11,  2.22,  3.33,  4.44,  5.55]])

In [57]:
col12_view

array([[ 2.5 ,  3.6 ],
       [22.5 , 33.6 ],
       [ 2.22,  3.33]])

In [58]:
col12_copy

array([[ 2.5 ,  3.5 ],
       [22.5 , 33.3 ],
       [ 2.22,  3.33]])

## Transforming arrays

### Transposing

Transposing is the operation of interchanging the axes of an array. The `T` attribute of array returns transpose of an array.   

In [59]:
a

array([10, 25, 35, 44, 55])

In [60]:
a.T

array([10, 25, 35, 44, 55])

Transposing has no effect on one dimensional array, as there is only one axis.

In [61]:
b

array([[ 1.5 ,  2.5 ,  3.6 ,  4.4 ,  5.5 ],
       [11.1 , 22.5 , 33.6 , 44.4 , 55.5 ],
       [ 1.11,  2.22,  3.33,  4.44,  5.55]])

In [62]:
b.T

array([[ 1.5 , 11.1 ,  1.11],
       [ 2.5 , 22.5 ,  2.22],
       [ 3.6 , 33.6 ,  3.33],
       [ 4.4 , 44.4 ,  4.44],
       [ 5.5 , 55.5 ,  5.55]])

On two-dimensioanl array (matrix), transpose of the array results in expected result.  

It is important to understand that a 1-d array is not a row vector or column vector. 
Both, row vector and column vectors are 2-d arrays. A row vector has shape (1, n), whereas a column vector has shape (m, 1).

#### Adding an axis

A 1-d array of shape (n,) can be transformed into a 2-d array of shape (1,n) or (n,1) by introducing a new axis as shown below.

In [63]:
arow = a[np.newaxis, :]
arow

array([[10, 25, 35, 44, 55]])

In [64]:
acolumn = a[:,np.newaxis]
acolumn

array([[10],
       [25],
       [35],
       [44],
       [55]])

In [65]:
arow.T

array([[10],
       [25],
       [35],
       [44],
       [55]])

In [66]:
acolumn.T

array([[10, 25, 35, 44, 55]])

#### `transpose` function/ method

Transpose can also be computed using `transpose` function of numpy or equivalently `transpose` method of ndarray.


<u>Note</u>: *Transpose is a view of the original array, irrespective of how it is obtained*


In [67]:
b

array([[ 1.5 ,  2.5 ,  3.6 ,  4.4 ,  5.5 ],
       [11.1 , 22.5 , 33.6 , 44.4 , 55.5 ],
       [ 1.11,  2.22,  3.33,  4.44,  5.55]])

In [68]:
np.transpose(b)

array([[ 1.5 , 11.1 ,  1.11],
       [ 2.5 , 22.5 ,  2.22],
       [ 3.6 , 33.6 ,  3.33],
       [ 4.4 , 44.4 ,  4.44],
       [ 5.5 , 55.5 ,  5.55]])

In [69]:
b.transpose()     # Same result as above

array([[ 1.5 , 11.1 ,  1.11],
       [ 2.5 , 22.5 ,  2.22],
       [ 3.6 , 33.6 ,  3.33],
       [ 4.4 , 44.4 ,  4.44],
       [ 5.5 , 55.5 ,  5.55]])

The transpose function is more general as it also accepts an axes parameter, a permutation of axes labels.
Thus, if the shape of x is (m, n, p), and we compute y as  
`	y = x.transpose (1, 0, 2)`  
and z as  
`	z = x.transpose (1, 2, 0)`  
then the shapes of y and z are (n, m, p) and (n, p, m).

[HW: See the methods swapaxes, ravel]


In [70]:
c = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
c      # Shape is (2, 2, 3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [71]:
c.transpose()    # shape is (3, 2, 2)

array([[[ 1,  7],
        [ 4, 10]],

       [[ 2,  8],
        [ 5, 11]],

       [[ 3,  9],
        [ 6, 12]]])

In [72]:
c.transpose(2, 1, 0)    # Same result as above

array([[[ 1,  7],
        [ 4, 10]],

       [[ 2,  8],
        [ 5, 11]],

       [[ 3,  9],
        [ 6, 12]]])

In [73]:
c.transpose(0, 2, 1)   # Shape is (2, 3, 2)

array([[[ 1,  4],
        [ 2,  5],
        [ 3,  6]],

       [[ 7, 10],
        [ 8, 11],
        [ 9, 12]]])

### Reshaping

Shape of an array can be changed using the `reshape` method as shown below.

In [74]:
x = np.arange(1, 7)
x

array([1, 2, 3, 4, 5, 6])

In [75]:
y = x.reshape(2, 3)
y

array([[1, 2, 3],
       [4, 5, 6]])

In [76]:
z = x.reshape(3, 2)
z

array([[1, 2],
       [3, 4],
       [5, 6]])

It should be noted that reshape method creates a view of the original array.

===== Additional examples discussed in class ======

In [77]:
b

array([[ 1.5 ,  2.5 ,  3.6 ,  4.4 ,  5.5 ],
       [11.1 , 22.5 , 33.6 , 44.4 , 55.5 ],
       [ 1.11,  2.22,  3.33,  4.44,  5.55]])

In [79]:
id1 = np.array([[0], [1]])
id2 = np.array([[0, 2, 4]])

In [80]:
id1

array([[0],
       [1]])

In [81]:
id2

array([[0, 2, 4]])

In [82]:
b[id1, id2]

array([[ 1.5,  3.6,  5.5],
       [11.1, 33.6, 55.5]])

In [83]:
b[np.ix_([0, 1], [0, 2, 4])]

array([[ 1.5,  3.6,  5.5],
       [11.1, 33.6, 55.5]])

In [84]:
a

array([10, 25, 35, 44, 55])

In [85]:
a[np.newaxis, :].shape

(1, 5)

In [86]:
a[:,np.newaxis].shape

(5, 1)

In [87]:
a[np.newaxis,:,np.newaxis].shape

(1, 5, 1)