
# Handwritten digit recognition using Single Layer NN

The input dataset `digits` consists of 8x8 pixel images of handwritten digits. The goal is to recognize a handwritten digit. 

* Since an input image has 8 x 8 pixels, we have totally 8x8 = 64 features in the dataset. 
* Also since there are 10 digits, the output layer (the only layer) consists of 10 neurons.

Therefore the weight matrix has the shape (64, 10).  

In [1]:
from sklearn import datasets
digits = datasets.load_digits()
X = digits.data
Y = digits.target
print(X.shape)
print(Y.shape)

(1797, 64)
(1797,)


Next we split the dataset randomly into training dataset and test dataset.

In [2]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.33)

## `MLPClassifier` 

`MLPClassifier` is a multilayer NN based classifier available in the `neural_network` module. This classifier is designed to solve multi-class classification problem.

Next we initialize the `MlPClassifier`.

In [3]:
from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier(
    hidden_layer_sizes=(),  # No hidden Layer
    alpha=0,
    solver="sgd",
    verbose=True,
    learning_rate_init=0.1,
)
mlp.fit(X_train, Y_train)

Iteration 1, loss = 18.22289732
Iteration 2, loss = 18.90258766
Iteration 3, loss = 7.21698742
Iteration 4, loss = 3.60271548
Iteration 5, loss = 2.18727180
Iteration 6, loss = 1.66369590
Iteration 7, loss = 1.22367224
Iteration 8, loss = 1.03924409
Iteration 9, loss = 1.05751346
Iteration 10, loss = 0.85721144
Iteration 11, loss = 0.73536822
Iteration 12, loss = 0.70962511
Iteration 13, loss = 0.63635816
Iteration 14, loss = 0.56852174
Iteration 15, loss = 0.49926645
Iteration 16, loss = 0.51095472
Iteration 17, loss = 0.46417317
Iteration 18, loss = 0.42132958
Iteration 19, loss = 0.41869454
Iteration 20, loss = 0.31748498
Iteration 21, loss = 3.46606933
Iteration 22, loss = 1.34250669
Iteration 23, loss = 0.99113015
Iteration 24, loss = 0.68866130
Iteration 25, loss = 0.59392578
Iteration 26, loss = 0.46921842
Iteration 27, loss = 0.43380799
Iteration 28, loss = 0.32825090
Iteration 29, loss = 0.31107282
Iteration 30, loss = 0.22561221
Iteration 31, loss = 0.18999015
Iteration 32, l

MLPClassifier(alpha=0, hidden_layer_sizes=(), learning_rate_init=0.1,
              solver='sgd', verbose=True)

In [4]:
import numpy as np
from sklearn import metrics
Y_pred = mlp.predict(X_test)
print('Accuracy = %0.4f'%np.mean(Y_pred == Y_test))
print("Confusion matrix:\n%s" % metrics.confusion_matrix(Y_test, Y_pred))

Accuracy = 0.9495
Confusion matrix:
[[57  0  0  0  0  1  0  0  0  0]
 [ 0 49  0  1  2  0  0  0  1  1]
 [ 0  0 57  0  0  0  0  0  0  0]
 [ 0  0  0 47  0  0  0  0  0  0]
 [ 0  4  0  0 68  0  0  0  0  0]
 [ 0  0  0  0  0 62  0  0  0  0]
 [ 0  0  0  0  2  0 52  0  1  0]
 [ 0  0  0  1  0  0  0 55  1  0]
 [ 0  0  0  5  0  3  0  0 51  3]
 [ 0  0  0  1  0  1  0  0  2 66]]


Class probabilities can be predicted using the `predict_proba` method as shown below.

In [14]:
mlp.predict_proba(X_test[np.newaxis, 0])

array([[9.12657890e-171, 3.81643305e-070, 1.01683703e-171,
        6.55023655e-212, 9.92632230e-077, 2.88341969e-124,
        1.07501095e-196, 1.00495687e-132, 1.00000000e+000,
        3.16991597e-092]])

In [13]:
mlp.predict(X_test[np.newaxis, 0])

array([8])