In [1]:
import matplotlib.pyplot as plt

# Load the digits dataset from datasets module
from sklearn import datasets
digits = datasets.load_digits()

In [2]:
print(digits.DESCR)

.. _digits_dataset:

Optical recognition of handwritten digits dataset
--------------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 1797
    :Number of Attributes: 64
    :Attribute Information: 8x8 image of integer pixels in the range 0..16.
    :Missing Attribute Values: None
    :Creator: E. Alpaydin (alpaydin '@' boun.edu.tr)
    :Date: July; 1998

This is a copy of the test set of the UCI ML hand-written digits datasets
https://archive.ics.uci.edu/ml/datasets/Optical+Recognition+of+Handwritten+Digits

The data set contains images of hand-written digits: 10 classes where
each class refers to a digit.

Preprocessing programs made available by NIST were used to extract
normalized bitmaps of handwritten digits from a preprinted form. From a
total of 43 people, 30 contributed to the training set and different 13
to the test set. 32x32 bitmaps are divided into nonoverlapping blocks of
4x4 and the number of on pixels are counted in each blo

In [3]:
X = digits.data
Y = digits.target
print(X.shape)
print(Y.shape)

(1797, 64)
(1797,)


In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, 
                                                    test_size=0.33, 
                                                    random_state = 87779 )

## Bayesian Classification Digit dataset


In [28]:
import pandas as pd
import numpy as np
from sklearn import metrics

In [30]:
# import Gaussian Naive Bayes classifier
from sklearn.naive_bayes import GaussianNB

# create a Gaussian Classifier
classifer = GaussianNB()

# training the model
classifer.fit(X_train, y_train)

# testing the model
y_pred = classifer.predict(X_test)

In [31]:

print('Accuracy = %0.4f'%np.mean(y_pred == y_test))
print("Confusion matrix:\n%s" % metrics.confusion_matrix(y_test, y_pred))

Accuracy = 0.8519
Confusion matrix:
[[56  0  0  0  2  0  0  0  0  0]
 [ 0 41  0  0  0  0  0  1 11  4]
 [ 0  3 44  0  0  0  0  0 13  0]
 [ 0  0  2 37  0  2  1  3  7  2]
 [ 0  0  0  0 53  0  2  5  1  0]
 [ 0  0  0  1  0 57  0  2  2  0]
 [ 0  1  1  0  0  0 57  0  0  0]
 [ 0  0  0  0  1  1  0 63  2  0]
 [ 0  1  0  0  0  1  0  0 53  0]
 [ 0  0  1  3  0  2  0  2  8 45]]


In [32]:
# importing classifier
from sklearn.naive_bayes import BernoulliNB

# initializaing the NB
classifer1 = BernoulliNB()

# training the model
classifer1.fit(X_train, y_train)

# testing the model
y_pred1 = classifer1.predict(X_test)

In [33]:
print('Accuracy = %0.4f'%np.mean(y_pred1 == y_test))
print("Confusion matrix:\n%s" % metrics.confusion_matrix(y_test, y_pred1))

Accuracy = 0.8754
Confusion matrix:
[[57  1  0  0  0  0  0  0  0  0]
 [ 0 34  3  0  3  0  1  1 10  5]
 [ 0  2 56  1  0  0  0  0  1  0]
 [ 0  0  2 44  0  1  0  1  3  3]
 [ 0  1  0  0 58  0  0  2  0  0]
 [ 1  1  0  4  0 52  0  0  1  3]
 [ 0  0  0  0  0  0 57  0  2  0]
 [ 0  0  0  0  1  0  0 64  1  1]
 [ 0  3  0  0  0  1  0  0 45  6]
 [ 0  1  0  4  1  0  0  1  1 53]]
