## Question 1

In [14]:
import numpy as np

np.random.seed(42)

mu, sigma = 10, 2 
s = np.random.normal(mu, sigma, 50)
print(f"The generated random numbers are: \n {s}")

mean = np.mean(s)
print(f"The mean of the generated random numbers is: {mean:.4f}")

variance = np.var(s)
print(f"The variance of the generated random numbers is: {variance:.4f}")

sd = np.std(s)
print(f"The standard deviation of the generated random numbers is: {sd:.4f}")

maximum = np.max(s)
print(f"The maximum of generated random numbers is : {maximum:.4f}")

minimum = np.min(s)
print(f"The minimum of generated random numbers is : {minimum:.4f}")

The generated random numbers are: 
 [10.99342831  9.7234714  11.29537708 13.04605971  9.53169325  9.53172609
 13.15842563 11.53486946  9.06105123 11.08512009  9.07316461  9.06854049
 10.48392454  6.17343951  6.55016433  8.87542494  7.97433776 10.62849467
  8.18395185  7.1753926  12.93129754  9.5484474  10.13505641  7.15050363
  8.91123455 10.22184518  7.69801285 10.75139604  8.79872262  9.4166125
  8.79658678 13.70455637  9.97300555  7.88457814 11.64508982  7.5583127
 10.41772719  6.08065975  7.3436279  10.39372247 11.47693316 10.34273656
  9.76870344  9.39779261  7.04295602  8.56031158  9.07872246 12.11424445
 10.68723658  6.47391969]
The mean of the generated random numbers is: 9.5491
The variance of the generated random numbers is: 3.4172
The standard deviation of the generated random numbers is: 1.8486
The maximum of generated random numbers is : 13.7046
The minimum of generated random numbers is : 6.0807


## Question 2:

In [29]:
array1 = np.array([[1,2], 
                   [3,4]])
print(f"Your first matrix is: \n {array1}")

array2 = np.array([[5,6], 
                   [7,8]])
print(f"Your second matrix is: \n {array2}")

print(f"The element wise addition of the arrays is: \n {array1 + array2}")
print(f"The element wise multiplication of the arrays is: \n {array1 * array2}")
print(f"The dot product of the arrays is: \n {np.dot(array1, array2)}")
print(f"The square of each element of first array is: \n {array1**2}")
print(f"The square of each element of second array is: \n {array2**2}")

Your first matrix is: 
 [[1 2]
 [3 4]]
Your second matrix is: 
 [[5 6]
 [7 8]]
The element wise addition of the arrays is: 
 [[ 6  8]
 [10 12]]
The element wise multiplication of the arrays is: 
 [[ 5 12]
 [21 32]]
The dot product of the arrays is: 
 [[19 22]
 [43 50]]
The square of each element of first array is: 
 [[ 1  4]
 [ 9 16]]
The square of each element of second array is: 
 [[25 36]
 [49 64]]


## Question 3:

In [37]:
matrix = []

print("Enter values for a 3x3 matrix:")

for i in range(3):
    row = list(map(int, input(f"Enter 3 numbers for row {i+1} separated by space: ").split()))
    matrix.append(row)

matrix = np.array(matrix)

print()

print("Matrix:")
print(matrix)
print()

transpose = np.transpose(matrix)
print(f"The transpose of the given matrix is: \n {transpose}")

print()

determinant = np.linalg.det(matrix)
print(f"The determinant of the given matrix is: {determinant}")

print()

inverse = np.linalg.inv(matrix)
print(f"The inverse of the given matrix is: \n {inverse}")

Enter values for a 3x3 matrix:


Enter 3 numbers for row 1 separated by space:  1 2 3
Enter 3 numbers for row 2 separated by space:  4 5 6
Enter 3 numbers for row 3 separated by space:  7 8 9



Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

The transpose of the given matrix is: 
 [[1 4 7]
 [2 5 8]
 [3 6 9]]

The determinant of the given matrix is: -9.51619735392994e-16

The inverse of the given matrix is: 
 [[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


## Question 4:

In [57]:
np.random.seed(69)

matrix2 = np.random.randint(0, 100, size = (4, 5))
print(f"The 4X5 matrix is: \n {matrix2}")

print()

second_row = matrix2[1:2]
print(f"The second row of the matrix is: \n {second_row}")

print()

third_column = matrix2[:,2:3]
print(f"The third column of the matrix is: \n {third_column}")

print()

submatrix = matrix2[1:3, 1:3]
print(f"The submatrix from the center is: \n {submatrix}")

The 4X5 matrix is: 
 [[54 75 73 90 55]
 [20 49 22  9 56]
 [97 38 96 88 12]
 [37 75 53  3 80]]

The second row of the matrix is: 
 [[20 49 22  9 56]]

The third column of the matrix is: 
 [[73]
 [22]
 [96]
 [53]]

The submatrix from the center is: 
 [[49 22]
 [38 96]]


## Question 5:

In [75]:
data = [15, 12, 13, 15, 18, 16, 19, 12, 20, 22, 36, 96, 59, 86, 78, 32, 45, 75, 65, 21, 42]
data_matrix = np.array(data)

print(f"The mean value of the given data is: {np.mean(data_matrix):.4f}")
print(f"The median value of the given data is: {np.median(data_matrix):.4f}")
print(f"The standard deviation value of the given data is: {np.std(data_matrix):.4f}")
print(f"The variance value of the given data is: {np.var(data_matrix):.4f}")
print(f"The coefficient of variation of the given data is: {(np.std(data_matrix)/np.mean(data_matrix)) * 100:.4f}")
print(f"The range value of the given data is: {np.ptp(data_matrix):.4f}")

import pandas as pd
dataframe = pd.DataFrame(data_matrix)
dataframe.describe()

The mean value of the given data is: 37.9524
The median value of the given data is: 22.0000
The standard deviation value of the given data is: 26.7804
The variance value of the given data is: 717.1882
The coefficient of variation of the given data is: 70.5631
The range value of the given data is: 84.0000


,0
count,21.000000
mean,37.952381
std,27.441713
min,12.000000
25%,16.000000
50%,22.000000
75%,59.000000
max,96.000000
